rename everything some urls remaining

diff --git a/bundler/bundle/install b/bundler/bundle/install
--- a/bundler/bundle/install
+++ b/bundler/bundle/install
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Installs TinyPilot and all dependencies.
+# Installs DELL_S2725HS and all dependencies.
 
 # Exit on first error.
 set -e
@@ -15,7 +15,6 @@ set -x
 if grep -q "boot=overlay" /proc/cmdline ; then
   echo 'The read-only filesystem is enabled.' >&2
   echo 'Disable the read-only filesystem before proceeding.' >&2
-  echo 'See https://tinypilotkvm.com/faq/read-only-filesystem for details.' >&2
   exit 1
 fi
 
@@ -28,7 +27,7 @@ else
   # Install only on Raspberry Pi 4 Model B.
   if ! grep --quiet "^Model\s*: Raspberry Pi 4 Model B" /proc/cpuinfo ; then
     echo 'You are trying to install on unsupported hardware.' >&2
-    echo 'Visit https://github.com/tiny-pilot/tinypilot/ for more details.' >&2
+    echo 'Visit https://github.com/Dell-S2725HS/DellS2725HS/ for more details.' >&2
     exit 1
   fi
 
@@ -38,23 +37,23 @@ else
   # open-source project). Similarly, the the 64-bit version of the Raspberry Pi
   # operating system is based on Debian and its distro ID would be "Debian".
   if [[ "$(lsb_release --id --short)" != 'Raspbian' ]]; then
-    echo "TinyPilot currently only supports the 32-bit version of Raspberry Pi OS 11 \"Bullseye\"." >&2
-    echo "To install TinyPilot, you'll need Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
+    echo "DELL_S2725HS currently only supports the 32-bit version of Raspberry Pi OS 11 \"Bullseye\"." >&2
+    echo "To install DELL_S2725HS, you'll need Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
     exit 1
   fi
 
   # Prevent installation on OS versions lower than Raspberry Pi OS 11 "Bullseye".
   if (( "$(lsb_release --release --short)" < 11 )); then
-    echo "TinyPilot no longer supports Raspberry Pi OS 10 \"Buster\" or lower." >&2
-    echo "To install TinyPilot, you'll need to upgrade your operating system to Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
+    echo "DELL_S2725HS no longer supports Raspberry Pi OS 10 \"Buster\" or lower." >&2
+    echo "To install DELL_S2725HS, you'll need to upgrade your operating system to Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
     exit 1
   fi
 
   # Prevent installation on Raspberry Pi OS 12 "Bookworm".
   if (( "$(lsb_release --release --short)" > 11 )); then
-    echo "TinyPilot is not yet compatible with Raspberry Pi OS 12 \"Bookworm\"." >&2
-    echo "You can track our progress by visiting https://github.com/tiny-pilot/tinypilot/issues/1668" >&2
-    echo "To install TinyPilot, you'll need to downgrade your operating system to Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
+    echo "DELL_S2725HS is not yet compatible with Raspberry Pi OS 12 \"Bookworm\"." >&2
+    echo "You can track our progress by visiting https://github.com/Dell-S2725HS/DellS2725HS/issues/1668" >&2
+    echo "To install DELL_S2725HS, you'll need to downgrade your operating system to Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
     exit 1
   fi
 fi
@@ -67,18 +66,18 @@ readonly JANUS_DEBIAN_PACKAGE
 USTREAMER_DEBIAN_PACKAGE="$(ls ustreamer*.deb)"
 readonly USTREAMER_DEBIAN_PACKAGE
 
-# Get the filename of the TinyPilot Debian package.
-TINYPILOT_DEBIAN_PACKAGE="$(ls tinypilot*.deb)"
-readonly TINYPILOT_DEBIAN_PACKAGE
+# Get the filename of the DELL_S2725HS Debian package.
+DELLS2725HS_DEBIAN_PACKAGE="$(ls DellS2725HS*.deb)"
+readonly DELLS2725HS_DEBIAN_PACKAGE
 
 # Update apt package index files, allowing the apt repos to change suite name.
-# See https://github.com/tiny-pilot/tinypilot/issues/764
+# See https://github.com/Dell-S2725HS/DellS2725HS/issues/764
 apt-get update --allow-releaseinfo-change-suite
 
 apt-get install -y \
   "./${JANUS_DEBIAN_PACKAGE}" \
   "./${USTREAMER_DEBIAN_PACKAGE}" \
-  "./${TINYPILOT_DEBIAN_PACKAGE}"
+  "./${DELLS2725HS_DEBIAN_PACKAGE}"
 
 # Install yq.
 mv yq /usr/bin/yq
diff --git a/bundler/create-bundle b/bundler/create-bundle
--- a/bundler/create-bundle
+++ b/bundler/create-bundle
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-# Creates a TinyPilot installation bundle from the bundle/ folder.
+# Creates a DELL_S2725HS installation bundle from the bundle/ folder.
 #
-# You have to provide the TinyPilot Debian package and place it in the `bundle/`
+# You have to provide the DELL_S2725HS Debian package and place it in the `bundle/`
 # folder. The script fetches all other required dependencies automatically.
 
 # Exit on first error.
@@ -25,46 +25,46 @@ readonly BUNDLE_DIR='bundle'
 readonly OUTPUT_DIR='dist'
 
 # Exclude the AMD64 package from the production bundle.
-rm -f "${BUNDLE_DIR}/tinypilot"*amd64.deb
+rm -f "${BUNDLE_DIR}/DellS2725HS"*amd64.deb
 
-# Ensure that a TinyPilot Debian package exists.
-if ! ls "${BUNDLE_DIR}/tinypilot"*armhf.deb 1> /dev/null 2>&1; then
-  echo 'Failed to create bundle: no TinyPilot Debian package found.' >&2
+# Ensure that a DELL_S2725HS Debian package exists.
+if ! ls "${BUNDLE_DIR}/DellS2725HS"*armhf.deb 1> /dev/null 2>&1; then
+  echo 'Failed to create bundle: no DELL_S2725HS Debian package found.' >&2
   exit 1
 fi
 
-# Prints the TinyPilot release version as populated in the Debian package. The
+# Prints the DELL_S2725HS release version as populated in the Debian package. The
 # Debian package stores the version string in a header field of its control
-# file. The header is named: `Tinypilot-Version`.
-print_tinypilot_version() {
+# file. The header is named: `Dell-S2725HS-Version`.
+print_DellS2725HS_version() {
   # Shellcheck incorrectly warns that the `${...}` placeholder in `--showformat`
   # doesn’t expand, due to the single-quotes. The format string is not meant to
   # contain a bash variable, though, the placeholder is specific to `dpkg-deb`.
   # shellcheck disable=SC2016
   dpkg-deb \
     --show \
-    --showformat '${Tinypilot-Version}' \
-    "${BUNDLE_DIR}/tinypilot"*armhf.deb
+    --showformat '${Dell-S2725HS-Version}' \
+    "${BUNDLE_DIR}/DellS2725HS"*armhf.deb
 }
 
 # Compose bundle file name, which consists of these hyphen-separated parts:
-# 1. `tinypilot`
-# 2. The TinyPilot variant: `community` or `pro`
+# 1. `DellS2725HS`
+# 2. The DELL_S2725HS variant: `community` or `pro`
 # 3. A timestamp (which allows lexical sorting of bundles by their file names).
-# 4. The SemVer-compliant TinyPilot version.
+# 4. The SemVer-compliant DELL_S2725HS version.
 # Examples for bundle names:
-# - `tinypilot-pro-20220620T1713Z-2.4.1.tgz` (Pro)
-# - `tinypilot-community-20220620T1611Z-1.8.0-23+649a6b2.tgz` (Community)
+# - `DellS2725HS-pro-20220620T1713Z-2.4.1.tgz` (Pro)
+# - `DellS2725HS-community-20220620T1611Z-1.8.0-23+649a6b2.tgz` (Community)
 TIMESTAMP="$(date --iso-8601=minutes | sed 's/[:-]//g' | sed 's/+0000/Z/g')"
 readonly TIMESTAMP
-TINYPILOT_VERSION="$(print_tinypilot_version)"
-readonly TINYPILOT_VERSION
-readonly TINYPILOT_VARIANT='community'
-readonly BUNDLE_FILENAME="tinypilot-${TINYPILOT_VARIANT}-${TIMESTAMP}-${TINYPILOT_VERSION}.tgz"
+DELLS2725HS_VERSION="$(print_DellS2725HS_version)"
+readonly DELLS2725HS_VERSION
+readonly DELLS2725HS_VARIANT='community'
+readonly BUNDLE_FILENAME="DellS2725HS-${DELLS2725HS_VARIANT}-${TIMESTAMP}-${DELLS2725HS_VERSION}.tgz"
 
 # Download Janus Bullseye Backports Debian package.
 # Note: before bumping the Janus package version, be sure to compare our Janus
-# systemd config file (debian-pkg/usr/share/tinypilot/janus.service) to that of
+# systemd config file (debian-pkg/usr/share/DellS2725HS/janus.service) to that of
 # upstream and verify that the diff is the same as before.
 wget \
   --directory-prefix="${BUNDLE_DIR}" \
@@ -73,7 +73,7 @@ wget \
 # Download uStreamer Debian package.
 wget \
   --directory-prefix="${BUNDLE_DIR}" \
-  https://github.com/tiny-pilot/ustreamer-debian/releases/download/6.36-20250505185120/ustreamer_6.36-20250505185120_armhf.deb
+  https://github.com/Dell-S2725HS/ustreamer-debian/releases/download/6.36-20250505185120/ustreamer_6.36-20250505185120_armhf.deb
 
 # Download yq binary
 wget \
